### PR TITLE
Update LICENSE.txt

### PR DESCRIPTION
**Pull request by spdegabrielle**
Change package licence notice as per 

https://blog.racket-lang.org/2019/11/completing-racket-s-relicensing-effort.html

### CODE REVIEW

**Comment by a11ce** [comment]
I don't think this one needs changing. Both components of `math-win32-x86_64` *are* LGPL, and the licensing for the Racket code is covered at the end of the top-level readme.

**Comment by a11ce** [comment]
Actually it might, but only the first paragraph (and keep the other notices). See `draw-aarch64-macosx-3/LICENSE.txt`.

**Comment by LiberalArtist** [comment]
I've added pointers that are about this repository, but not directly about this pull request, over at https://github.com/racket/racket/issues/4270#issuecomment-1141461337

**Comment by Aeva** [comment]
I think it would be best if `math-win32-x86_64` wasn't marked as being LGPL because that way if you remove the dlls but for some reason still pull in the racket package on accident, you don't end up with something that is still technically a license violation in some situations.  This avoids creating ambiguity.

That said, it would be nice if racket's top level README indicated better how to properly avoid pulling in Racket's optional third party dependencies with conflicting licenses.

**Comment by samth** [comment]
@Aeva Can you be more precise about what you're suggesting here? All the Racket code in this repository is already licensed permissively. The LICENSE.txt file should clearly say _something_ about the license of the included files, which is the LGPL in the case of that package. Is there some way in particular that you would like it to be phrased?

**Comment by spdegabrielle** [comment]
> That said, it would be nice if racket's top level README indicated better how to properly avoid pulling in Racket's optional third party dependencies with conflicting licenses.

Maybe the listing of relevant packages in [LICENSE.txt](https://github.com/racket/racket/blob/master/LICENSE.txt#L33) should cover all packages with divergent licences?

**Comment by samth** [comment]
I think it's this line that should change: https://github.com/racket/racket/blob/master/LICENSE.txt#L30

That's correct about the _Racket source code_ of those packages, but not about the binary dependencies that Racket also distributes. I didn't think about this at the time because on Linux this doesn't come up.

**Comment by Aeva** [comment]
> @Aeva Can you be more precise about what you're suggesting here? All the Racket code in this repository is already licensed permissively. The LICENSE.txt file should clearly say _something_ about the license of the included files, which is the LGPL in the case of that package. Is there some way in particular that you would like it to be phrased?

I wrote that under the mistaken assumption that the package had an FFI wrapper to provide a racket interface to the DLLs or such and wasn't just DLLs and metadata.

**Comment by spdegabrielle** [comment]
I’m sorry - I’m not sure of the outcome of this PR?
Is it ok to close, or is a change required? I’m happy to change the pr, or bin it and do a new one.

**Comment by LiberalArtist** [comment]
I think there are some changes needed, roughly:

1. List the specific licenses for each binary library;
2. Add corresponding metadata to the `info.rkt` files; and
3. Most significantly, do likewise for all of the other packages in this repository.

I may be able to dig in to this some more in the next few days. I put some notes on the above in https://github.com/racket/racket/issues/4270#issuecomment-1141461337.

Additionally, this should be merged by someone with the necessary credentials to upload updated packages to Racket's S3 bucket.

In the mean time, I'd suggest leaving this open so we don't loose track of it.

**Comment by LiberalArtist** [comment]
I'm working on https://github.com/racket/libs/pull/4, which should take care of this.

**Comment by LiberalArtist** [comment]
I think this can be closed now, since #4 was merged.

**Comment by spdegabrielle** [comment]
thank you @LiberalArtist

**Pull request closed without merging**
